cloudflare-project: "aptispace-template"

project:
  type: website
  output-dir: _site

  pre-render: bash _extensions/aptitek/download-fonts/download_fonts.sh
  resources:
    - "lab/**"
    - "assets/**"

filters:
  - filetree
  - card

website:
  title: "Template"
  # DÉSACTIVER l'indexation (Anti-Google)
  search: false
  site-url: "https://template.apti.space"

  
  sidebar:
    # --- CONFIGURATION BRANDING ---
    logo: "assets/logo.svg"          # Chemin vers l'image
    logo-href: "https://aptitek.io"  # Redirection externe vers votre site
    logo-alt: "Aptitek"              # Texte alternatif pour l'accessibilité
    # ------------------------------
    style: "docked"
    search: false
    
    contents: auto

format:
  html:
    theme:
      - solar        # On garde la structure de base propre
      - .theme/theme.scss
    mainfont: "Recursive"
    monofont: "Recursive"
    # Active la coloration syntaxique Solarized native pour le code
    highlight-style: solarized
    toc: true            # Table des matières automatique
    code-copy: true      # Bouton "copier" sur les blocs de code
    code-tools:
      source: true
      toggle: false
      caption: "Voir le code source"
    mermaid:
      theme: neutral
    html-math-method: katex
    
    # Injection pour bloquer les robots d'indexation
    header-includes: |
      <meta name="robots" content="noindex, nofollow">

    include-after-body: assets/fix_links.html

  typst:
    toc: true
    number-sections: true
    font-paths:
      - "fonts"
    mainfont: "Recursive Sans Linear"
    papersize: a4